.TH lavalauncher 1 lavalauncher-0.1
.SH NAME
LavaLauncher - A simple launcher for Wayland desktops


.SH DESCRIPTION
LavaLauncher serves a single purpose: Letting the user execute shell commands
by clicking on icons on a dynamically sized bar, placed at one of the screen
edges.
.P
The Wayland compositor must implement the Layer-Shell for LavaLauncher to work.
If LavaLauncher is displayed but wont respond to clicks, chances are that the
compositor you are using only displays Layer-Shell surfaces but does not forward
events to them.


.SH SYNOPSIS
.B lavalauncher
.RB [options...]


.SH OPTIONS
.TP
.B \-a
Enable aggressive anchoring.
Some compositors, like sway, do not respect the exclusive area of layer surfaces
that are only anchored to less then three sides. Aggressive anchoring will
always anchor the bar surface to three sides to work around this.
.TP
.B \-b <path> <command>
Add a button. Path is the path to an image file. Command is the shell command
executed when the user clicks on the button.
.TP
.B \-l <overlay|top|bottom|background>
Layer the bar surface.
.TP
.B \-p <top|right|bottom|left>
Position of the bar.
.TP
.B \-s <size>
Width of the bar in pixel.
.TP
.B \-S <size>
Width of the border in pixel.
.TP
.B \-c <colour>
Colour of the bar in the format #RRGGBBAA.
.TP
.B \-C <colour>
Colour of the border in the format #RRGGBBAA.
.TP
.B \-h
Display a helpful help message and exit.
.TP
.B \-v
Verbose output.


.SH EXAMPLE
lavalauncher
\-b /home/leon/.config/icons/firefox.png firefox
\-b /home/leon/.config/icons/glenda.png acme
\-p bottom
\-s 80
\-S 2
\-c "#20202088"
\-C "#FFFFFFFF"


.SH MAILINGLIST
You can send bug reports / fixes, patches and user feedback to the mailinglist.

.B <~leon_plickat/lavalauncher@lists.sr.ht>


.SH AUTHORS
Leon Plickat <leonhenrik.plickat@stud.uni-goettingen.de>
